services:
  accountsdb:
    container_name: accountsdb
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  chatdb:
    container_name: chatdb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/var/lib/mongodb/data

  goapp:
    container_name: goapp
    image: goapp:1.0.0
    build:
      context: ./go-server
      dockerfile: go.dockerfile
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@accountsdb:5432/postgres?sslmode=disable'
    ports:
      - '8000:8000'
    depends_on:
      - accountsdb

  springbootapp:
    container_name: springbootapp
    build:
      context: ./spring-server
      dockerfile: spring.dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - chatdb

volumes:
  pgdata: {}
  mongo-data: {}
