services:
  accounts_backend:
    container_name: accounts_backend
    image: go_accounts_backend:1.0.0
    build:
      context: ./accounts-backend
      dockerfile: go.dockerfile
    environment:
      DATABASE_URL: 'postgres://admin:admin@35.239.202.252:5432/postgres?sslmode=disable'
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    ports:
      - '8000:8000'

  chat_backend:
    container_name: chat_backend
    image: go_chat_backend:1.0.0
    build:
      context: ./chat-backend
      dockerfile: go.dockerfile
    environment:
      DATABASE_URL: 'mongodb+srv://admin:admin@cluster0.vbfhlso.mongodb.net/'
    ports:
      - '8002:8002'

  ws_server:
    container_name: ws_server
    image: go_ws:1.0.0
    build:
      context: ./ws-server
      dockerfile: go.dockerfile
    ports:
      - '8001:8001'

  client_frontend:
    container_name: client_frontend
    image: express_client_frondend:1.0.0
    build:
      context: ./client-frontend
      dockerfile: node.dockerfile
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
    ports:
      - '3000:3000'

volumes:
  pgdata: {}
  mongo-data: {}
