services:
  springbootapp:
    container_name: springbootapp
    build:
      context: ./spring-server
      dockerfile: spring.dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - chatdb

  chatdb:
    container_name: chatdb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/var/lib/mongodb/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    healthcheck:
      test: ["CMD", "mongo", "--eval", "'db.stats().ok'"]
      interval: 30s
      timeout: 10s
      retries: 5

  goapp:
    container_name: goapp
    image: goapp:1.0.0
    build:
      context: ./go-server
      dockerfile: go.dockerfile
    environment:
      DATABASE_URL: 'postgres://postgres:postgres@accountsdb:5432/postgres?sslmode=disable'
    ports:
      - '8000:8000'
    depends_on:
      - accountsdb

  accountsdb:
    container_name: accountsdb
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
  mongo-data: {}
